/*Global Renewable Energy Asset Intelligence System (GREAIS)

	1. Find total energy generated by each plant.*/
    SELECT plant_id,ROUND(sum(energy_generated_mwh),2) AS Total_energy_genrated 
    FROM energy_generation GROUP BY plant_id;
    
-- 2. Find top 10 plants with highest efficiency.
    select plant_id from energy_generation order by efficiency_percent DESC LIMIT 10;

-- 3. Calculate total revenue generated country-wise.
	select p.country,round(sum(e.revenue_usd),2) as Total_revenue
    from energy_sales e join plant_master p
    on e.plant_id=p.plant_id group by p.country;

-- 4. Find plants with downtime greater than 100 hours.
	select plant_id, downtime_hours from maintenance_logs where downtime_hours >=70;
	
-- 5. Find average maintenance cost by maintenance type.
	select maintenance_type,avg(maintenance_cost ) as AVG_cost
    from maintenance_logs group by maintenance_type;

-- 6. Find monthly energy generation trend for each country.
	select p.country,extract(year from e.datetime) as gen_year,
		   extract(month from e.datetime) as gen_month,
           sum(e.energy_generated_mwh) AS total_energy
    from energy_generation e join plant_master p
    on e.plant_id=p.plant_id
    group by p.country,gen_year,gen_month;
    
    
-- 7. Identify plants whose efficiency dropped below 60%.
		select e.plant_id,e.efficiency_percent,p.plant_name
        from energy_generation e join plant_master p
        on e.plant_id=p.plant_id
        where e.efficiency_percent<60;
        
-- 8. Find top 5 countries generating highest carbon credits.
	select distinct(p.country), c.plant_id,c.credits_generated
    from carbon_credits c join plant_master p
    on c.plant_id=p.plant_id
    order by c.credits_generated desc limit 5;
    
-- 9. Calculate yearly revenue growth percentage.
with yearly_revenue as (
	select extract(year from sale_date) sales_year,
			sum(revenue_usd) as total_revenue
	from energy_sales group by extract(year from sale_date)
)
select sales_year,total_revenue ,
	lag(total_revenue) over(order by sales_year) as previeus_revenue,
   round( total_revenue-lag(total_revenue) over(order by sales_year) /
    lag(total_revenue) over(order by sales_year) *100,2)
    as revenue_growth

from  yearly_revenue
order by sales_year;

    
-- 10. Find plants having more than 3 grid failures in a month.
SELECT 
    p.plant_id,
    p.plant_name,
    EXTRACT(YEAR FROM f.failure_date) AS failure_year,
    EXTRACT(MONTH FROM f.failure_date) AS failure_month,
    COUNT(f.failure_id) AS total_failures
FROM grid_failures f INNER JOIN  plant_master p ON f.plant_id = p.plant_id
GROUP BY  p.plant_id,
    p.plant_name,
    EXTRACT(YEAR FROM f.failure_date),
    EXTRACT(MONTH FROM f.failure_date)
HAVING COUNT(f.failure_id) > 3
ORDER BY 
    failure_year DESC, 
    failure_month DESC, 
    total_failures DESC;
    

-- 11. Calculate average temperature impact on solar energy generation.
	select avg(temperature) as AVG_temperature from sensor_readings;

-- 12. Find cumulative revenue generated by each plant.
	select revenue_usd,plant_id from energy_sales;

SELECT 
    plant_id,
    sale_date,
    revenue_usd,
    SUM(revenue_usd) OVER (
        PARTITION BY plant_id 
        ORDER BY sale_date
    ) AS cumulative_revenue
FROM 
    energy_sales;



-- 13. Find most expensive maintenance issue category.
	select maintenance_type, sum(maintenance_cost) as total 
	from maintenance_logs group by maintenance_type order by total DESC limit 1 ;

-- 14. Find correlation between downtime and revenue loss.
WITH CombinedLosses AS (
    SELECT 
        plant_id,
        SUM(downtime_hours) AS total_downtime_hours,
        SUM(financial_loss_usd) AS total_loss_usd
    FROM (
        SELECT plant_id, downtime_hours, 0 AS financial_loss_usd FROM maintenance_logs
        UNION ALL
        SELECT plant_id, outage_hours AS downtime_hours, financial_loss_usd FROM grid_failures
    ) combined
    GROUP BY plant_id
)
SELECT 
    CORR(total_downtime_hours, total_loss_usd) AS correlation_coefficient
FROM CombinedLosses;

-- 15. Identify plants operating above 95% efficiency continuously for 30 days.
WITH RankedEfficiency AS (
    SELECT 
        plant_id,
        CAST(datetime AS DATE) AS gen_date,
        ROW_NUMBER() OVER(PARTITION BY plant_id ORDER BY datetime) - 
        ROW_NUMBER() OVER(PARTITION BY plant_id, (CASE WHEN efficiency_percent > 95 THEN 1 ELSE 0 END) ORDER BY datetime) AS streak_group
    FROM energy_generation
),
StreakDurations AS (
    SELECT 
        plant_id,
        COUNT(DISTINCT gen_date) AS continuous_days
    FROM RankedEfficiency
    GROUP BY plant_id, streak_group
)
SELECT DISTINCT p.plant_id, p.plant_name
FROM StreakDurations s
JOIN plant_master p ON s.plant_id = p.plant_id
WHERE s.continuous_days >= 5;

 -- 16. Rank plants within each country based on profitability.
 WITH PlantFinancials AS (
    SELECT 
        p.plant_id,
        p.plant_name,
        p.country,
        COALESCE((SELECT SUM(revenue_usd) FROM energy_sales WHERE plant_id = p.plant_id), 0) +
        COALESCE((SELECT SUM(credits_generated * market_price_usd) FROM carbon_credits WHERE plant_id = p.plant_id), 0) -
        COALESCE((SELECT SUM(maintenance_cost) FROM maintenance_logs WHERE plant_id = p.plant_id), 0) -
        COALESCE((SELECT SUM(financial_loss_usd) FROM grid_failures WHERE plant_id = p.plant_id), 0) AS total_profit
    FROM plant_master p
)
SELECT 
    country,
    plant_name,
    total_profit,
    DENSE_RANK() OVER (PARTITION BY country ORDER BY total_profit DESC) AS profitability_rank
FROM PlantFinancials;

-- 17. Detect anomaly periods where sensor vibration exceeded normal threshold.
WITH VibrationStats AS (
    SELECT 
        AVG(vibration_level) AS avg_vib,
        STDDEV(vibration_level) AS stddev_vib
    FROM sensor_readings
)
SELECT 
    s.plant_id,
    p.plant_name,
    s.timestamp,
    s.vibration_level,
    (vs.avg_vib + (3 * vs.stddev_vib)) AS upper_threshold_limit
FROM sensor_readings s
JOIN plant_master p ON s.plant_id = p.plant_id
CROSS JOIN VibrationStats vs
WHERE s.vibration_level > (vs.avg_vib + (3 * vs.stddev_vib))
ORDER BY s.timestamp DESC;


-- 18. Find predictive maintenance indicators using sensor readings.
WITH MovingAverages AS (
    SELECT 
        plant_id,
        timestamp,
        temperature,
        vibration_level,
        AVG(temperature) OVER(PARTITION BY plant_id ORDER BY timestamp RANGE BETWEEN INTERVAL '3' HOUR PRECEDING AND CURRENT ROW) AS rolling_avg_temp,
        AVG(vibration_level) OVER(PARTITION BY plant_id ORDER BY timestamp RANGE BETWEEN INTERVAL '3' HOUR PRECEDING AND CURRENT ROW) AS rolling_avg_vib,
        AVG(temperature) OVER(PARTITION BY plant_id) AS historic_avg_temp,
        AVG(vibration_level) OVER(PARTITION BY plant_id) AS historic_avg_vib
    FROM sensor_readings
)
SELECT 
    plant_id,
    timestamp,
    'High Temp Spike' AS warning_trigger
FROM MovingAverages 
WHERE rolling_avg_temp > (historic_avg_temp * 1.25) -- 25% spike
UNION ALL
SELECT 
    plant_id,
    timestamp,
    'High Vibration Spike' AS warning_trigger
FROM MovingAverages 
WHERE rolling_avg_vib > (historic_avg_vib * 1.30);

-- 19. Create rolling 7-day average energy production trend.
WITH DailyGeneration AS (
    SELECT 
        plant_id,
        CAST(datetime AS DATE) AS gen_date,
        SUM(energy_generated_mwh) AS daily_total_mwh
    FROM energy_generation
    GROUP BY plant_id, CAST(datetime AS DATE)
)
SELECT 
    plant_id,
    gen_date,
    daily_total_mwh,
    AVG(daily_total_mwh) OVER(
        PARTITION BY plant_id 
        ORDER BY gen_date 
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS rolling_7day_avg_mwh
FROM DailyGeneration
ORDER BY plant_id, gen_date;

-- 20. Build a complete profitability report:
with revenue_CTE as (
	select plant_id, round(sum(revenue_usd),2) as total_revenue from energy_sales group by plant_id
),
financial_loss_CTE as(
	select plant_id, round(sum(financial_loss_usd),2) as total_financial_loss_usd from grid_failures group by plant_id
),
maintenance_cost_CTE as(
select plant_id, round(sum(maintenance_cost),2) as total_maintenance_cost from maintenance_logs group by plant_id
)
select
	*, dense_rank() over(order by profit desc) as profit_rank
from (select
		country,
		pm.plant_id, 
		plant_name,
        plant_type,
        total_revenue as revenue,
        total_financial_loss_usd as financial_loss_usd,
        total_maintenance_cost as maintenance_cost,
		round(total_revenue - total_financial_loss_usd - total_maintenance_cost,2) as profit
	from plant_master as pm
	join revenue_CTE as r on pm.plant_id = r.plant_id
	join financial_loss_CTE as fc on pm.plant_id = fc.plant_id
	join maintenance_cost_CTE as mc on pm.plant_id = mc.plant_id) as ans
order by profit_rank;

